// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npczuelwcfnqrktdhvnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wY3p1ZWx3Y2ZucXJrdGRodm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDE1NDksImV4cCI6MjA2MDI3NzU0OX0.p4bBEQlcnaCzubfWARzR3-e7X2iDPc7eYCDBNRGc61Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);